# Copy from BB's blog XD
dist: focal
branches:
  only:
    - master

language: go

install:
- wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.68.3/hugo_extended_0.68.3_Linux-64bit.deb
- sudo dpkg -i /tmp/hugo.deb

script:
  - HUGO_ENV=production hugo --gc --minify -v


deploy:
  strategy: git
  repo: omeletwithomeletwithoutegg.github.io
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master

notifications:
  email:
      recipients:
        - 2qbingxuan@gmail.com
      on_success: always
      on_failure: always
